### PR TITLE
Add script to detect foul words

### PR DESCRIPTION
**Pull request by bingyuanng**
Added
- script to detect foul words

### CODE REVIEW

**Comment by althras** [comment]
Yerrr... can we not have this? Younger people swear all the time - it's not necessarily meant in negativity, and typically ppl don't take offense from it.

**Comment by althras** [comment]
We can have a 'report to admin' function of some kind. Would make more sense.

**Comment by bingyuanng** [comment]
ah. okay. Let me revert this.

**Comment by bingyuanng** [comment]
But it will only trigger a response with a message `@username Language!`. I figure it would help police people to not use foul word.

**Comment by althras** [comment]
That assumes that policing people not to use foul words in a blanket kind of way is the right thing to do.

We shouldn't use personal attacks, insult each other, call each other names, etc - sure. These are universal standards to keep a community friendly and fine. But swearing to expressively say something ain't a big deal these days.

Refer the opening sequence of Avengers Age of Ultron :P

**Pull request merged**
