### PR TITLE
added role-based permission filter

### PR DESCRIPTION
**Pull request by Tajam**
I added two temporary testing command. Can test it in hackerspace server first.

### CODE REVIEW

**Comment by bingyuanng** [comment]
Maybe you would like to update the readme file to show to document how to use. ?

**Comment by Tajam** [comment]
Make another section for #Development?

**Comment by bingyuanng** [comment]
Yeah. Sure. While u are at it can you add that permission line into the generator `program.sh` as well?

**Comment by Tajam** [comment]
I didn't plan to add it because the `permission` property is optional.

**Comment by bingyuanng** [comment]
I see. Okay.

**Comment by Tajam** [comment]
Updated `readme.md`

**Pull request merged**
